os: linux
dist: xenial
language: python
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python demo.py --figure_suffix svg
  - mkdir -p build
  - cp parameter.json build/
  - python schema.py --table_format html
